'use strict';
var util = require('./utils');

module.exports = {
    app: 'src/main/webapp/',
    dist: 'target',
    port: 9000,                 // browser sync port
    apiPort: 8080,              // web app port
    liveReloadPort: 35729,      // ?
    uri: 'http://localhost:',
    constantTemplate:
        '\n// DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
        '<% constants.forEach(function(constant) { %>export const <%- constant.name %> = <%= constant.value %>;\n<% }) %>' +
        '\n'
};
